### ISSUE TITLE
"tagline"

### ISSUE THREAD

**Issue by vincerubinetti** [manubot/manubot.org#1] opened 2019-05-14 19:00 UTC
Would be good to have a standardized "tagline" for Manubot. @dhimmel @slochower @agitter Suggestions would be nice. We should have a short one -- 4 to 5 words -- that can fit in the document title/tab, and we can also have a longer one -- 10 to 20 words -- that will appear underneath the logo right up front.

Here are some of my off-the-cuff ideas:
- The future of scholarly publishing
- Automated publishing for the future
- Academic publishing for the new age

Ideally something that captures the main purpose/point of manubot existing, as well as some of its more essential features. Naturally it'll be impossible to capture everything it does, so just the most important stuff up front.

**Comment by cgreene** [comment] 2019-05-14 19:11
* Publishing, automated.

**Comment by slochower** [comment] 2019-05-14 20:21
I think @cgreene 's suggestion is good, because it eliminates the need to add "for the future" or "new age."

**Comment by agitter** [comment] 2019-05-15 11:25
I also like @cgreene's suggestion.

**Comment by vincerubinetti** [comment] 2019-05-15 16:27
I like the format of "Publishing, ___". Short and to the point. But it seems like Manubot is a lot more than just automation. Perhaps we can come up with a more general descriptor, like "Publishing, revolutionized." (except not as overly grandiose).

Unless you guys feel like "automation" is indeed the key purpose and selling point of Manubot.

**Comment by dhimmel** [comment] 2019-05-17 20:28
## Existing taglines

Here are some existing taglines we've used:

+ from [manbut/manubot README](https://github.com/manubot/manubot/blob/37a9c69ad8d74d51ee3cff7779b2b6d303629c07/README.md): "The manuscript bot for automated scholarly publishing"
+ from [rootstock README](https://github.com/manubot/rootstock/tree/dcb3cc43880694acf4ea25774fabe328f20c3adb): "Automated scholarly manuscripts on GitHub"
+  current @manubot organization description: "Next generation of scholarly publishing: open, collaborative, reproducible, free"
+ from [these slides](https://slides.com/dhimmel/manubot): "powering the next generation of scholarly manuscript"
+ from [PSB2019 slides](https://slides.com/dhimmel/psb): "next generation publishing"
+ from [FORCE2018 slides](https://slides.com/dhimmel/force2018): "a foreshadow of publishing's future"

I don't have any particular attachment to these existing taglines, but wanted to list them.

Does it make sense to have two taglines, one short (~ 2 words) and one long (~ 6 words)? @vincerubinetti where do you see each one being used? Should a long one encompass the short one like "publishing, automated: making manuscripts open, collaborative, reproducible & free"?

**Comment by agitter** [comment] 2019-05-18 19:46
Having a very short and slighter longer version makes sense.  If we use "publishing, automated" as the very short version, it is harder to extend into a phrase.  The other keywords don't directly relate to automation.  I still like it as the short tagline though.

A longer phrase could be something like "Publishing, revolutionized: making manuscripts automated, open, collaborative, reproducible, and free".  I agree that "revolutionized" may be a bit much though.

**Comment by vincerubinetti** [comment] 2019-05-20 13:31
I think the short and long versions can written to be together or apart. Whatever we can come up with.

@dhimmel The short version would be used in very condensed spaces, like in the tab title, or on business cards/stickers/magnets, or on powerpoint slides, or possibly wherever you have the logo and room for a bit of text.

The longer version would probably mostly just be for the website. It'd be somewhere near the top of the page, and would also be in the website `<meta>` description which is what shows up on google under the link. It could also go in slides about manubot as a quick description.

`Authoring, reformed.` is another variant I came up with. "Reformed sounds a bit stiff but it's the only other adjective in the thesaurus I could find that was general enough to capture all of it without sounding to grand. "Authoring" also might be a little more accurate in terms of the workflow of manubot?

**Comment by dhimmel** [comment] 2019-05-20 16:07
- publishing, reinvented
- publishing, automated
- publishing, the smart way
- publishing, the modern way
- publishing, the open way
- modern publishing, automated
- publishing, fulfilled 
- publishing, perfected

Currently, the tagline at https://www.authorea.com/ is "A powerful publishing platform for articles, data, figures, preprints" and "The best features for modern research publishing".

The tagline at https://www.overleaf.com/ is "LaTeX, Evolved. The easy to use, online, collaborative LaTeX editor". I like how Overleaf's short tagline works well with its long tagline.

**Comment by slochower** [comment] 2019-05-22 01:48
Of the latest list, I like:

- publishing, automated
- publishing, open & immediate
- immediate transparent publishing

I think a key part of Manubot is not _just_ the publishing, but the writing and the communication. In particular, the ability to comment inline on PRs and have substantial discussion in Issues. Those points are, in my opinion, not obvious from a tag line that is just about "publishing." Having said that, I'm not sure how to include them. Maybe we could find a way to work in something about "community" into the tagline.

**Comment by agitter** [comment] 2019-05-22 11:42
I like the keywords "open" or "transparent" as a way to suggest the workflow @slochower mentioned that Manubot enables.  I suggest we avoid "perfected" because it could invite complaints about an active project that will always have room to improve.

**Comment by dhimmel** [comment] 2019-05-22 12:01
Another option could be "open manuscripts, automated" or "open collaborative manuscripts".

**Comment by agitter** [comment] 2019-05-23 14:43
Playing around with the ordering in @dhimmel's latest:

"Manuscripts, open and automated.  Making publishing continuous, interactive, and reproducible."

Do we want to use "publication" instead of "publishing" to match https://greenelab.github.io/meta-review/#continuous-publication?  "Interactive" is an important term because of the interactivity of HTML manuscripts and interactions among authors and reader.  The last sentence our abstract gives other adjectives that could be used in the longer form.

**Comment by vincerubinetti** [comment] 2019-05-28 15:00
I think "Manuscripts, open and automated" is the one. To me, those are the two key points of Manubot. And those word choices are simple enough to be public/advertising/laymen-friendly, and general enough to capture multiple things.

As for the long-form tagline, to me, the key points would be: "Collaborative, continuous, interactive, versioned, reproducible, and free of charge."

**Comment by agitter** [comment] 2019-05-28 18:02
@vincerubinetti what do you think about replacing "_next generation_" in your long form with something else?  In some settings I dislike next generation because it will inevitably become stale.  I agree with everything else in your summary and long tagline.

**Comment by vincerubinetti** [comment] 2019-05-29 14:07
I could take it or leave it. I think it's just a nice succinct, easy-to-understand way of saying "this thing operates in a new and different way that we think is better".

We could just go with:

"A tool set and workflow for scholarly publishing that is open, collaborative, continuous, automated, reproducible, and free"

Now that I think of it, it might be good to state that it's a tool set and workflow here as to not be vague about what it is. This is what will show up in google search results, so we should clear as to what manubot actually is (is it just a philosophy, is it a platform/marketplace of scholarly articles, is it an aggregate of third party tools, is it one monolithic program like ms word -- people wont know).

**Comment by dhimmel** [comment] 2019-05-29 17:54
I am happy with:

**short**:
Manuscripts, open and automated

**long**:
A tool set and workflow for scholarly publishing that is open, collaborative, continuous, automated, reproducible, and free

**Comment by vincerubinetti** [comment] 2019-05-30 13:54
One last minor thing. I thought we would go with "Publishing, open and automated" rather than "Manuscripts, open and automated". 

Maybe manuscripts is slightly more accurate, but isn't publishing the main thing we're trying to make easier. Manubot is a process/workflow, not a thing. It seems better to have an action rather than a noun. If we do use "manuscripts", the wording would feel less awkward if it was just "Open and automated manuscripts."

Also, just from the title "manubot" I think it's somewhat obvious that "manuscripts" are involved.

**Comment by agitter** [comment] 2019-05-30 14:04
> Also, just from the title "manubot" I think it's somewhat obvious that "manuscripts" are involved.

I'm not sure it is obvious.  I don't think we actually state that Manubot is short for "Manuscript bot" anywhere.  Modernizing "publishing" can mean many things - like replacing journals with other ways of sharing and reviewing manuscripts that have been written elsewhere - so I thought "Manuscripts" was more directly relevant to the Manubot workflow.

"Open and automated manuscripts" also sounds okay to me.

**Comment by vincerubinetti** [comment] 2019-05-30 14:13
I guess there is no verb that accurately captures all of the parts of the process that manubot covers. If there was a word that covered "writing/authoring", "reviewing", and "distributing/publishing", that would be ideal. I guess I thought "publishing" was the most important of those and could sort of hand-wavingly be stretched to mean all of them, at least enough to give the right split second impression for first time viewers. People seemed to be okay with it when it was first mentioned by Casey, which I think shows the importance of going with a gut impression and not overthinking things. But if you think using "publishing" could be misleading or construed as false advertising to those deeply in academics, we don't have to use it. cc @dhimmel

**Comment by dhimmel** [comment] 2019-05-30 14:18
I think manuscripts is a lot more accurate than publishing, since publishing can mean a variety of things from publishing pamphlets to movies. Therefore, I'm leaning towards manuscripts because I think it will do a better job of telling the user what Manubot does. Therefore, one of the following options for short title?

- open, automated manuscripts
- manuscripts, open and automated
- open and automated manuscripts
- open & automated manuscripts

With the long title, we use "scholarly publishing", which adds the necessary qualifications to publishing. I kind of liked having the short say manuscripts and the long say "scholarly publishing". Also I think I am slightly in favor of switching to "scholarly publication".

**Comment by vincerubinetti** [comment] 2019-05-30 14:24
@dhimmel I'm okay with any of those. 

I don't really know the difference between "publishing" and "publication", but the former sounds better/clearer/simpler to me.

**Comment by dhimmel** [comment] 2019-05-30 15:17
> I don't really know the difference between "publishing" and "publication"

We discuss the distinction in https://github.com/greenelab/meta-review/pull/216, where we decided to use "continuous publication" rather than "continuous publishing".

From https://wikidiff.com/publishing/publication:

> As nouns the difference between publishing and publication is that publishing is the industry of publishing, including the production and distribution of books, magazines, web sites, newspapers, etc while publication is the act of publishing printed or other matter.

**Comment by agitter** [comment] 2019-06-03 16:17
Should we consider this closed by 14fd2de0be732794508ac62cbe7ecb40c088c41e?

**Closed** 2019-06-03 17:07 UTC
